/**
 * Script to generate static TypeScript schema files from OpenAPI YAML files.
 * Run with: npm run generate-schemas
 *
 * Generates schema_v<version>.ts files in the src/schemas/ directory, each exporting
 * a VersionSchema object with all schemas pre-extracted from the corresponding YAML.
 */

import path from 'path';
import fs from 'fs/promises';
import { OpenApiSchemaExtractor } from '../src/_old/schema-extractor';
import type { VersionSchema } from '../src/schemas/index';

const SCHEMAS_DIR = path.resolve(__dirname, '..', 'schemas');
const OUTPUT_DIR = path.resolve(__dirname, '..', 'src', 'schemas');

async function buildSchema(extractor: OpenApiSchemaExtractor): Promise<VersionSchema> {
  const allSchemas = extractor.getAllSchemas();

  let events: VersionSchema['events'];
  try {
    events = {
      fulfilled: extractor.createJsonSchemaWithDefinitions('RequestFulfilledEvent'),
      rejected: extractor.createJsonSchemaWithDefinitions('RequestRejectedEvent'),
      created: extractor.createJsonSchemaWithDefinitions('RequestCreatedEvent'),
      published: extractor.createJsonSchemaWithDefinitions('PublishedEvent'),
    };
  } catch {
    events = undefined;
  }

  return {
    productFootprint: extractor.createJsonSchemaWithDefinitions('ProductFootprint'),
    authTokenResponse: {
      type: 'object',
      properties: {
        access_token: { type: 'string' },
      },
      required: ['access_token'],
    },
    simpleListFootprintResponse: {
      type: 'object',
      properties: {
        data: {
          type: 'array',
          minItems: 1,
          items: {
            type: 'object',
            properties: { id: { type: 'string' } },
            required: ['id'],
          },
        },
      },
      required: ['data'],
    },
    emptyResponse: {
      type: 'object',
      properties: {
        data: {
          type: 'array',
          maxItems: 0,
          items: { type: 'object' },
        },
      },
      required: ['data'],
    },
    simpleGetFootprintResponse: {
      type: 'object',
      properties: {
        data: {
          type: 'object',
          properties: { id: { type: 'string' } },
          required: ['id'],
        },
      },
      required: ['data'],
    },
    listFootprintResponse: {
      $schema: 'http://json-schema.org/draft-07/schema#',
      title: 'ListFootprintsResponse',
      type: 'object',
      required: ['data'],
      properties: {
        data: {
          type: 'array',
          items: { $ref: '#/definitions/ProductFootprint' },
        },
      },
      definitions: allSchemas,
    },
    getFootprintResponse: {
      $schema: 'http://json-schema.org/draft-07/schema#',
      title: 'SingleFootprintResponse',
      type: 'object',
      required: ['data'],
      properties: {
        data: { $ref: '#/definitions/ProductFootprint' },
      },
      definitions: allSchemas,
    },
    events,
  };
}

function renderSchema(schema: VersionSchema, versionUnderscore: string, versionDot: string): string {
  return `// This file is auto-generated by scripts/generate-schemas.ts. Do not edit manually.
// Source: schemas/openapi_v${versionUnderscore}.yaml (PACT v${versionDot})
import type { VersionSchema } from '../../schemas/index';

const schema: VersionSchema = ${JSON.stringify(schema, null, 2)};

export default schema;
`;
}

async function generateSchemaFile(yamlFile: string): Promise<void> {
  const match = yamlFile.match(/openapi_v(\d+_\d+)\.yaml$/);
  if (!match) return;

  const versionUnderscore = match[1];
  const versionDot = versionUnderscore.replace('_', '.');

  const yamlPath = path.join(SCHEMAS_DIR, yamlFile);
  const outputPath = path.join(OUTPUT_DIR, `schema_v${versionUnderscore}.ts`);

  console.log(`Generating schema_v${versionUnderscore}.ts from ${yamlFile}...`);

  const extractor = await OpenApiSchemaExtractor.create(yamlPath);
  const schema = await buildSchema(extractor);
  const content = renderSchema(schema, versionUnderscore, versionDot);

  await fs.writeFile(outputPath, content, 'utf8');
  console.log(`  ✓ src/schemas/schema_v${versionUnderscore}.ts`);
}

async function main(): Promise<void> {
  await fs.mkdir(OUTPUT_DIR, { recursive: true });

  const files = await fs.readdir(SCHEMAS_DIR);
  const yamlFiles = files
    .filter(f => /^openapi_v\d+_\d+\.yaml$/.test(f))
    .sort();

  if (yamlFiles.length === 0) {
    console.error('No OpenAPI YAML schema files found in schemas/');
    process.exit(1);
  }

  console.log(`Found ${yamlFiles.length} YAML file(s). Generating schema files...\n`);
  await Promise.all(yamlFiles.map(generateSchemaFile));
  console.log('\nDone.');
}

main().catch(err => {
  console.error(err);
  process.exit(1);
});
