/**
 * Script to generate static TypeScript schema files from OpenAPI YAML files.
 * Run with: npm run generate-schemas
 *
 * Generates schema.ts files in src/v{version}/ directories, each exporting
 * a Schema object with all schemas pre-extracted from the corresponding YAML.
 */

import path from 'path';
import fs from 'fs/promises';
import { OpenApiSchemaExtractor } from './schema-extractor';
import type { Schema } from '../src/common/schema';

const SCHEMAS_DIR = path.resolve(__dirname, '..', 'schemas');
const SRC_DIR = path.resolve(__dirname, '..', 'src');

async function buildSchema(extractor: OpenApiSchemaExtractor): Promise<Schema> {
  const allSchemas = extractor.getAllSchemas();

  function tryExtract(name: string): any {
    try { return extractor.createJsonSchemaWithDefinitions(name); } catch { return undefined; }
  }

  return {
    ProductFootprint: extractor.createJsonSchemaWithDefinitions('ProductFootprint'),
    AuthTokenResponse: {
      type: 'object',
      properties: {
        access_token: { type: 'string' },
      },
      required: ['access_token'],
    },
    SimpleListFootprintResponse: {
      type: 'object',
      properties: {
        data: {
          type: 'array',
          minItems: 1,
          items: {
            type: 'object',
            properties: { id: { type: 'string' } },
            required: ['id'],
          },
        },
      },
      required: ['data'],
    },
    EmptyResponse: {
      type: 'object',
      properties: {
        data: {
          type: 'array',
          maxItems: 0,
          items: { type: 'object' },
        },
      },
      required: ['data'],
    },
    SimpleGetFootprintResponse: {
      type: 'object',
      properties: {
        data: {
          type: 'object',
          properties: { id: { type: 'string' } },
          required: ['id'],
        },
      },
      required: ['data'],
    },
    ListFootprintResponse: {
      $schema: 'http://json-schema.org/draft-07/schema#',
      title: 'ListFootprintsResponse',
      type: 'object',
      required: ['data'],
      properties: {
        data: {
          type: 'array',
          items: { $ref: '#/definitions/ProductFootprint' },
        },
      },
      definitions: allSchemas,
    },
    GetFootprintResponse: {
      $schema: 'http://json-schema.org/draft-07/schema#',
      title: 'SingleFootprintResponse',
      type: 'object',
      required: ['data'],
      properties: {
        data: { $ref: '#/definitions/ProductFootprint' },
      },
      definitions: allSchemas,
    },
    RequestCreatedEvent: tryExtract('RequestCreatedEvent'),
    RequestFulfilledEvent: tryExtract('RequestFulfilledEvent'),
    RequestRejectedEvent: tryExtract('RequestRejectedEvent'),
    PublishedEvent: tryExtract('PublishedEvent'),
  };
}

function renderSchema(schema: Schema, versionUnderscore: string, versionDot: string): string {
  return `// This file is auto-generated by scripts/generate-schemas.ts. Do not edit manually.
// Source: schemas/openapi_v${versionUnderscore}.yaml (PACT v${versionDot})
import type { Schema } from '../common/schema';

export const schema: Schema = ${JSON.stringify(schema, null, 2)};

`;
}

async function generateSchemaFile(yamlFile: string): Promise<void> {
  const match = yamlFile.match(/openapi_v(\d+_\d+)\.yaml$/);
  if (!match) return;

  const versionUnderscore = match[1];
  const versionDot = versionUnderscore.replace('_', '.');

  const yamlPath = path.join(SCHEMAS_DIR, yamlFile);
  const versionFolder = `v${versionUnderscore}`;
  const outputDir = path.join(SRC_DIR, versionFolder);
  const outputPath = path.join(outputDir, 'schema.ts');

  console.log(`Generating ${versionFolder}/schema.ts from ${yamlFile}...`);

  const extractor = await OpenApiSchemaExtractor.create(yamlPath);
  const schema = await buildSchema(extractor);
  const content = renderSchema(schema, versionUnderscore, versionDot);

  await fs.mkdir(outputDir, { recursive: true });
  await fs.writeFile(outputPath, content, 'utf8');
  console.log(`  ✓ src/${versionFolder}/schema.ts`);
}

async function main(): Promise<void> {
  await fs.mkdir(SRC_DIR, { recursive: true });

  const files = await fs.readdir(SCHEMAS_DIR);
  const yamlFiles = files
    .filter(f => /^openapi_v\d+_\d+\.yaml$/.test(f))
    .sort();

  if (yamlFiles.length === 0) {
    console.error('No OpenAPI YAML schema files found in schemas/');
    process.exit(1);
  }

  console.log(`Found ${yamlFiles.length} YAML file(s). Generating schema files...\n`);
  await Promise.all(yamlFiles.map(generateSchemaFile));
  console.log('\nDone.');
}

main().catch(err => {
  console.error(err);
  process.exit(1);
});
