"""PACT data model — Pydantic models generated from the OpenAPI specs.

The ``v*_*`` modules are auto-generated by ``codegen.py`` from the OpenAPI
specifications in ``packages/pact-data-model/schemas`` (the shared source of
truth). Do not edit them by hand — re-run ``python codegen.py``.

    from pact_api_client.models import v3_0, v2_3
    from pact_api_client.models.v3_0 import ProductFootprint
"""

from . import v2_0, v2_1, v2_2, v2_3, v3_0

__all__ = ["v2_0", "v2_1", "v2_2", "v2_3", "v3_0"]
