// This file is auto-generated by scripts/generate-types.ts. Do not edit manually.

export enum ProductFootprintStatus {
  Active = "Active",
  Deprecated = "Deprecated",
}

export enum CarbonFootprintDeclaredUnit {
  Liter = "liter",
  Kilogram = "kilogram",
  CubicMeter = "cubic meter",
  KilowattHour = "kilowatt hour",
  Megajoule = "megajoule",
  TonKilometer = "ton kilometer",
  SquareMeter = "square meter",
}

export enum CarbonFootprintCharacterizationFactors {
  AR6 = "AR6",
  AR5 = "AR5",
}

export enum CarbonFootprintCrossSectoralStandardsUsed {
  GHGProtocolProductStandard = "GHG Protocol Product standard",
  ISOStandard14067 = "ISO Standard 14067",
  ISOStandard14044 = "ISO Standard 14044",
}

export enum CarbonFootprintBiogenicAccountingMethodology {
  PEF = "PEF",
  ISO = "ISO",
  GHGP = "GHGP",
  Quantis = "Quantis",
}

export enum CarbonFootprintGeographyRegionOrSubregion {
  Africa = "Africa",
  Americas = "Americas",
  Asia = "Asia",
  Europe = "Europe",
  Oceania = "Oceania",
  AustraliaAndNewZealand = "Australia and New Zealand",
  CentralAsia = "Central Asia",
  EasternAsia = "Eastern Asia",
  EasternEurope = "Eastern Europe",
  LatinAmericaAndTheCaribbean = "Latin America and the Caribbean",
  Melanesia = "Melanesia",
  Micronesia = "Micronesia",
  NorthernAfrica = "Northern Africa",
  NorthernAmerica = "Northern America",
  NorthernEurope = "Northern Europe",
  Polynesia = "Polynesia",
  SouthEasternAsia = "South-eastern Asia",
  SouthernAsia = "Southern Asia",
  SouthernEurope = "Southern Europe",
  SubSaharanAfrica = "Sub-Saharan Africa",
  WesternAsia = "Western Asia",
  WesternEurope = "Western Europe",
}

export enum ProductOrSectorSpecificRuleOperator {
  PEF = "PEF",
  EPDInternational = "EPD International",
  Other = "Other",
}

export enum AssuranceCoverage {
  CorporateLevel = "corporate level",
  ProductLine = "product line",
  PCFSystem = "PCF system",
  ProductLevel = "product level",
}

export enum AssuranceLevel {
  Limited = "limited",
  Reasonable = "reasonable",
}

export enum AssuranceBoundary {
  GateToGate = "Gate-to-Gate",
  CradleToGate = "Cradle-to-Gate",
}

export enum ErrorCode {
  BadRequest = "BadRequest",
  AccessDenied = "AccessDenied",
  TokenExpired = "TokenExpired",
  NotFound = "NotFound",
  InternalError = "InternalError",
  NotImplemented = "NotImplemented",
}

export type Urn = string;

export type FloatBetween1And3 = number;

/** `ProductFootprint` is a data type which represents the carbon footprint of a product under a specific scope ([[#dt-carbonfootprint-scope]]) and with values calculated in accordance with the [=PACT Methodology=]. The objective of a `ProductFootprint` is to provide interoperability between the creator (the [=data owner=]) and the consumer (the [=data recipient=]) of ProductFootprints. The details on the exchange of ProductFootprints are specified in [[#api]]. Conceptually, the data type <{ProductFootprint}> is modeled as a multi-purpose container for product-specific emissions factors which is supported by extensibility through [=Data Model Extensions=]. Data Model Extensions enable [=data owners=] to exchange additional information related to a product with [=data recipients=]. The details are specified in [[#datamodelextension]] as well as [[!EXTENSIONS-GUIDANCE]], and [[!DATA-MODEL-EXTENSIONS]]. Each `ProductFootprint` can and should be updated over time, for instance to incorporate new or refined data from [=data owners=] (see [[#lifecycle]]). */
export interface ProductFootprint {
  /** A unique identifier that a system uses to refer to the entire dataset of the PCF. This is typically an automatically-generated number by the technology solution to maintain the required technical references to data within the system. UUID v4 [RFC4122](https://tools.ietf.org/html/rfc4122). */
  id: string;
  /** The version of the PACT Tech Specs that the data being shared complies with. This is a string in the format of "major.minor.patch" (e.g. "3.0.0"). */
  specVersion: string;
  /** A given PCF may change over time, due to updates to the calculation. This field lists all id's that reflect "past versions" of the current PCF. This is typically an automatically generated field of unique identifiers, maintained by the technology solution. */
  precedingPfIds?: string[];
  /** The version number of the PCF; if changes are made to the PCF, this version number will increment. */
  version: number;
  /** The date and time when the PCF was created. This is typically an automatically generated field by the software solution. */
  created: string;
  /** The date and time when the PCF was last updated. This is typically an automatically generated field by the software solution. If the data has never been updated, do not include this property. */
  updated?: string;
  /** The status of the PCF. `Active` means that the PCF is the most recent version and is the one that can be used CAN be used by a data recipients, e.g. for product footprint calculations. `Deprecated` means that the PCF is no longer the most recent version and SHOULD NOT be used by data recipients. See [[#lifecycle]] for details. */
  status: ProductFootprintStatus;
  /** TODO: Move this description to #lifecycle If defined, a descriptive reasoning explaining the current status of the PCF, what was changed since the last version, etc. If the PCF was changed since a previous version, indicate all methodological and/or production process change(s) that occurred to result in the PCF change. For example, include the relevant change(s) from the list below: Methodological: - Access to new Emission Factor data (database, supplier-specific, company-specific) - Updated upstream data (i.e. upstream supplier updated their PCF based on methodology change) Production Process: - Change in process - Change in feedstock - Change from conventional to certified sustainable material - Change in energy source - Change in upstream supplier - Updated upstream data (i.e. upstream supplier updated their PCF based on process change) See [[#lifecycle]] for details. */
  statusComment?: string;
  /** TODO: Create a separate paragraph on validity period and reference period The <dfn>validity period</dfn> is the time interval during which the ProductFootprint is declared as valid for use by a receiving [=data recipient=]. The validity period is OPTIONAL defined by the properties <{ProductFootprint/validityPeriodStart}> (including) and <{ProductFootprint/validityPeriodEnd}> (excluding). If no validity period is specified, the ProductFootprint is valid for 3 years starting with <{CarbonFootprint/referencePeriodEnd}>. If a validity period is to be specified, then 1. the value of <{ProductFootprint/validityPeriodStart}> MUST be defined with value greater than or equal to the value of <{CarbonFootprint/referencePeriodEnd}>. 2. the value of <{ProductFootprint/validityPeriodEnd}> MUST be defined with value 1. strictly greater than <{ProductFootprint/validityPeriodStart}>, and 2. less than or equal to <{CarbonFootprint/referencePeriodEnd}> + 3 years. */
  validityPeriodStart?: string;
  /** The end date and time of the validity period. See validityPeriodStart for more details. */
  validityPeriodEnd?: string;
  /** The name of the company that is the ProductFootprint Data Owner */
  companyName: string;
  /** The non-empty set of Uniform Resource Names ([[!RFC8141|URN]]). Each value of this set is supposed to uniquely identify the ProductFootprint Data Owner. TODO: See Company Identifier section for details */
  companyIds: Urn[];
  /** The free-form description of the product, including any additional relevant information such as production technology, packaging, process, feedstock and technical parameters (e.g. dimensions). Products which are services (i.e. consulting) should include a short description of the service. */
  productDescription: string;
  /** The non-empty set of [=ProductIds=] in [=URN=] format. Each of the values in the set is supposed to uniquely identify the product. See {#product-identifiers} for syntax and examples. */
  productIds: Urn[];
  /** Advisement: DEPRECATED in 3.0. Superseded by <{ProductFootprint/productClassifications}>. The UN Central Product Classification (CPC) that the given product belongs to. */
  productCategoryCpc: string;
  /** The non-empty trade name of the product. */
  productNameCompany: string;
  /** Advisement: OPTIONAL in 3.0. Additional information related to the product footprint. Whereas the property <{ProductFootprint/productDescription}> contains product-level information, <{ProductFootprint/comment}> SHOULD be used for information and instructions related to the calculation of the footprint, or other information which informs the ability to interpret, to audit or to verify the Product Footprint. */
  comment: string;
  /** The carbon footprint of the given product with value conforming to the data type <{CarbonFootprint}>. */
  pcf: CarbonFootprint;
  /** If defined, 1 or more data model extensions associated with the ProductFootprint. See <{DataModelExtension}> for details. */
  extensions?: DataModelExtension[];
}

/** A CarbonFootprint represents the carbon footprint of a product and related data in accordance with the [=PACT Methodology=]. ### Scope of a CarbonFootprint ### {#dt-carbonfootprint-scope} Each CarbonFootprint is scoped by 1. Time Period: the time period is defined by the properties <{CarbonFootprint/referencePeriodStart}> and <{CarbonFootprint/referencePeriodEnd}> (see [=PACT Methodology=] section 6.1.2.1) 2. Geography: further set by the properties <{CarbonFootprint/geographyRegionOrSubregion}>, <{CarbonFootprint/geographyCountry}>, and <{CarbonFootprint/geographyCountrySubdivision}> (see [=PACT Methodology=] section 6.1.2.2) If a CarbonFootprint 1. Has geographical granularity `Global`, then the properties <{CarbonFootprint/geographyCountry}> and <{CarbonFootprint/geographyRegionOrSubregion}> and <{CarbonFootprint/geographyCountrySubdivision}> MUST be `undefined`; 2. Has a regional or sub-regional geographical granularity, then the property <{CarbonFootprint/geographyRegionOrSubregion}> MUST be `defined` and the properties <{CarbonFootprint/geographyCountry}> and <{CarbonFootprint/geographyCountrySubdivision}> MUST be `undefined`; 3. Has a country-specific geographical granularity, then property <{CarbonFootprint/geographyCountry}> MUST be `defined` AND the properties <{CarbonFootprint/geographyRegionOrSubregion}> and <{CarbonFootprint/geographyCountrySubdivision}> MUST be `undefined`; 4. Has a country subdivision-specific geographical granularity, then property <{CarbonFootprint/geographyCountrySubdivision}> MUST be `defined` AND the properties <{CarbonFootprint/geographyRegionOrSubregion}> and <{CarbonFootprint/geographyCountry}> MUST be `undefined`. */
export interface CarbonFootprint {
  /** The unit of analysis of the product. See Data Type {{DeclaredUnit}} for further information. */
  declaredUnit: CarbonFootprintDeclaredUnit;
  /** The amount of <{CarbonFootprint/declaredUnit|Declared Units}> contained within the product to which the [[#carbonfootprint|PCF]] is referring to. The value MUST be strictly greater than `0`. */
  unitaryProductAmount: string;
  /** The product carbon footprint of the product <i>excluding</i> biogenic CO2 emissions. TODO: The value MUST be calculated per <{CarbonFootprint/declaredUnit|declared unit}> with unit `kg of CO2 equivalent per declared unit` (`kgCO2e / declaredUnit`), expressed as a [=decimal=] equal to or greater than zero. */
  pCfExcludingBiogenic: string;
  /** If present, the product carbon footprint of the product <i>including all</i> biogenic emissions (CO2 and otherwise). TODO: The value MUST be calculated per <{CarbonFootprint/declaredUnit|declared unit}> with unit `kg of CO2 equivalent per declared unit` (`kgCO2e / declaredUnit`), expressed as a [=decimal=]. Note: the value of this property can be less than `0` (zero). */
  pCfIncludingBiogenic?: string;
  /** The emissions from fossil sources as a result of fuel combustion, from fugitive emissions, and from process emissions. TODO: The value MUST be calculated per <{CarbonFootprint/declaredUnit|declared unit}> with unit `kg of CO2 equivalent per declared unit` (`kgCO2e / declaredUnit`), expressed as a [=decimal=] equal to or greater than zero. */
  fossilGhgEmissions: string;
  /** The fossil carbon content of the product (mass of carbon). TODO: The value MUST be calculated per <{CarbonFootprint/declaredUnit|declared unit}> with unit `kg Carbon per declared unit` (`kgC / declaredUnit`), expressed as a [=decimal=] equal to or greater than zero. */
  fossilCarbonContent: string;
  /** The biogenic carbon content of the product (mass of carbon). TODO: The value MUST be calculated per <{CarbonFootprint/declaredUnit|declared unit}> with unit `kg Carbon per declared unit` (`kgC / declaredUnit`), expressed as a [=decimal=] equal to or greater than zero. */
  biogenicCarbonContent: string;
  /** If present, emissions resulting from recent (i.e., previous 20 years) carbon stock loss due to land conversion directly on the area of land under consideration. The value of this property MUST include direct land use change (dLUC) where available, otherwise statistical land use change (sLUC) can be used. TODO: The value MUST be calculated per <{CarbonFootprint/declaredUnit|declared unit}> with unit `kg of CO2 equivalent per declared unit` (`kgCO2e / declaredUnit`), expressed as a [=decimal=] equal to or greater than zero. See [=PACT Methodology=] (Appendix B) for details. */
  dLucGhgEmissions?: string;
  /** If present, GHG emissions and removals associated with land-management-related changes, including non-CO2 sources. TODO: The value MUST be calculated per <{CarbonFootprint/declaredUnit|declared unit}> with unit `kg of CO2 equivalent per declared unit` (`kgCO2e / declaredUnit`), expressed as a [=decimal=]. */
  landManagementGhgEmissions?: string;
  /** If present, all other biogenic GHG emissions associated with product manufacturing and transport that are not included in dLUC (<{CarbonFootprint/dLucGhgEmissions}>), iLUC (<{CarbonFootprint/iLucGhgEmissions}>), and land management (<{CarbonFootprint/landManagementGhgEmissions}>). TODO: The value MUST be calculated per <{CarbonFootprint/declaredUnit|declared unit}> with unit `kg of CO2 equivalent per declared unit` (`kgCO2e / declaredUnit`), expressed as a [=decimal=] equal to or greater than zero. */
  otherBiogenicGhgEmissions?: string;
  /** If present, emissions resulting from recent (i.e., previous 20 years) carbon stock loss due to land conversion on land not owned or controlled by the company or in its supply chain, induced by change in demand for products produced or sourced by the company. TODO: The value MUST be calculated per <{CarbonFootprint/declaredUnit|declared unit}> with unit `kg of CO2 equivalent per declared unit` (`kgCO2e / declaredUnit`), expressed as a [=decimal=] equal to or greater than zero. See [=PACT Methodology=] (Appendix B) for details. */
  iLucGhgEmissions?: string;
  /** If present, the Biogenic Carbon contained in the product converted to kilogram of CO2e. TODO: The value MUST be calculated per <{CarbonFootprint/declaredUnit|declared unit}> with unit `kgCO2e / declaredUnit` expressed as a [=decimal=] equal to or <i>less than</i> zero. */
  biogenicCarbonWithdrawal?: string;
  /** If present, the GHG emissions resulting from aircraft engine usage for the transport of the product, excluding radiative forcing. TODO: The value MUST be calculated per <{CarbonFootprint/declaredUnit|declared unit}> with unit `kg of CO2 equivalent per declared unit` (`kgCO2e / declaredUnit`), expressed as a [=decimal=] equal to or greater than zero. */
  aircraftGhgEmissions?: string;
  /** A boolean flag indicating whether packaging emissions are included in the PCF (<{CarbonFootprint/pCfExcludingBiogenic}>, <{CarbonFootprint/pCfIncludingBiogenic}>). */
  packagingEmissionsIncluded: boolean;
  /** Emissions resulting from the packaging of the product. TODO: If present, the value MUST be calculated per <{CarbonFootprint/declaredUnit|declared unit}> with unit `kg of CO2 equivalent per kilogram` (`kgCO2e / declared unit`), expressed as a [=decimal=] equal to or greater than zero. The value MUST NOT be defined if <{CarbonFootprint/packagingEmissionsIncluded}> is `false`. */
  packagingGhgEmissions?: string;
  /** Advisement: DEPRECATED in 3.0. Superseded by <{CarbonFootprint/ipccCharacterizationFactorsSources}>. The IPCC version of the GWP characterization factors used in the calculation of the PCF (see [=PACT Methodology=] Section 3.2.2). In case several characterization factors are used, indicate the earliest version used in your calculations, disregarding supplier provided PCFs. The value MUST be one of the following: `AR6`, `AR5`. @deprecated */
  characterizationFactors: CarbonFootprintCharacterizationFactors;
  /** The characterization factors from one or more IPCC Assessment Reports used in the calculation of the PCF (see [=PACT Methodology=] Section 3.2.2). It MUST be a non-empty set of strings with the format `AR$VERSION$`, where `$VERSION$` stands for the IPCC report version number and MUST be an integer. Example values: <div class=example>["AR6"]</div> <div class=example>["AR5", "AR6"]</div> Per the Methodology the latest available characterization factor version shall be used, i.e., `["AR6"]`. In the event this is not possible, include the set of all characterization factors used. Advisement: Supersedes `characterizationFactors` deprecated in version 2.3. */
  ipccCharacterizationFactorsSources: string[];
  /** The cross sectoral standard(s) used as a basis for the PCF calculation. If multiple apply, list all. @deprecated */
  crossSectoralStandardsUsed: CarbonFootprintCrossSectoralStandardsUsed[];
  /** The product-specific or sector-specific rules applied for calculating or allocating GHG emissions. If no product or sector specific rules were followed, this set MUST be empty. */
  productOrSectorSpecificRules?: ProductOrSectorSpecificRule[];
  /** The standard followed to account for biogenic emissions and removals. If defined, the value SHOULD be one of the following: : `PEF` :: for the EU [Product Environmental Footprint Guide](https://ec.europa.eu/environment/archives/eussd/pdf/footprint/PEF%20methodology%20final%20draft.pdf) : `ISO` :: For the ISO 14067 standard : `GHGP` :: For the Greenhouse Gas Protocol (GHGP) Land sector and Removals Guidance : `Quantis` :: For the Quantis [Accounting for Natural Climate Solutions](https://quantis.com/report/accounting-for-natural-climate-solutions-guidance/) Guidance The enumeration of standards above will be evolved in future revisions. Account for this when implementing the validation of this property. */
  biogenicAccountingMethodology?: CarbonFootprintBiogenicAccountingMethodology;
  /** Advisement: OPTIONAL in 3.0. The processes attributable to each lifecycle stage. For example: electricity consumption included as an input in the production phase */
  boundaryProcessesDescription: string;
  /** The start (including) of the time boundary for which the PCF value is considered to be representative. Specifically, this start date represents the earliest date from which activity data was collected to include in the PCF calculation. See the [=PACT Methodology=] section 6.1.2.1 for further details. Can also be referred to as 'reporting period'. */
  referencePeriodStart: string;
  /** The end (excluding) of the time boundary for which the PCF value is considered to be representative. Specifically, this end date represents the latest date from which activity data was collected to include in the PCF calculation. Can al See the [=PACT Methodology=] section 6.1.2.1 for further details. Can also be referred to as 'reporting period'. */
  referencePeriodEnd: string;
  /** If present, the value MUST conform to data type {{RegionOrSubregion}}. See [[#dt-carbonfootprint-scope]] for further details. Additionally, see the [=PACT Methodology=] Section 6.1.2.2. */
  geographyRegionOrSubregion?: CarbonFootprintGeographyRegionOrSubregion;
  /** If present, the value MUST conform to data type [=ISO3166CC=]. See [[#dt-carbonfootprint-scope]] for further details. */
  geographyCountry?: string;
  /** If present, a ISO 3166-2 Subdivision Code. See [[#dt-carbonfootprint-scope]] for further details. */
  geographyCountrySubdivision?: string;
  /** If secondary data was used to calculate the <{CarbonFootprint}>, then it MUST include the property <{CarbonFootprint/secondaryEmissionFactorSources}> with value the emission factors used for the <{CarbonFootprint}> calculation. If no secondary data is used, this property MUST BE undefined. */
  secondaryEmissionFactorSources?: EmissionFactorDatabases[];
  /** The percentage of emissions excluded from PCF, expressed as a decimal number. See [=PACT Methodology=]. Advisement: [=Decimal=] in 3.0, was Number in 2.x */
  exemptedEmissionsPercent: number;
  /** Advisement: OPTIONAL in 3.0. Rationale behind exclusion of specific PCF emissions, CAN be the empty string if no emissions were excluded. */
  exemptedEmissionsDescription: string;
  /** If present, a description of any allocation rules applied and the rationale explaining how the selected approach aligns with [=PACT Methodology=] rules (see Section 3.3.1.4). */
  allocationRulesDescription?: string;
  /** If present, the results, key drivers, and a short qualitative description of the uncertainty assessment. */
  uncertaintyAssessmentDescription?: string;
  /** The share of primary data in percent. See the [=PACT Methodology=] Sections 4.2.1 and 4.2.2, Appendix B. For reference periods ending before the beginning of year 2025, at least property <{CarbonFootprint/primaryDataShare}> or propery <{CarbonFootprint/dqi}> MUST be defined. For reference periods including the beginning of year 2025 or after, this property MUST be defined. Advisement: [=Decimal=] in 3.0, was Number in 2.x */
  primaryDataShare?: number;
  /** If present, the Data Quality Indicators (dqi) in accordance with the [=PACT Methodology=] Sections 4.2.1 and 4.2.3, Appendix B. For reference periods ending before the beginning of year 2025, at least property <{CarbonFootprint/primaryDataShare}> or propery <{CarbonFootprint/dqi}> MUST be defined. For reference periods including the beginning of year 2025 or after, this property MUST be defined. */
  dqi?: DataQualityIndicators;
  /** If present, the Assurance information in accordance with the [=PACT Methodology=]. */
  assurance?: Assurance;
}

/** Each data model extension MUST be a valid JSON object conforming with the [JSON Representation of a Data Model Extension](https://wbcsd.github.io/data-model-extensions/spec/#instantiation). See [[!DATA-MODEL-EXTENSIONS]] for technical details and [[!EXTENSIONS-GUIDANCE]] for data model extension guidance. */
export interface DataModelExtension {
  /** The version of the Data Model Extension specification. The value MUST be a string in the format major.minor.patch as defined in Semantic Versioning 2.0.0. */
  specVersion: string;
  /** The value MUST be the URL to the publicly accessible Extension Schema File */
  dataSchema: string;
  /** The value MUST be the URL to the publicly accessible Extension Documentation. */
  documentation?: string;
  /** The value MUST be a JSON Object that conforms to the extension schema file referenced by the dataSchema property. */
  data: Record<string, unknown>;
}

/** A ProductOrSectorSpecificRule refers to a set of product or sector specific rules published by a specific operator and applied during product carbon footprint calculation. */
export interface ProductOrSectorSpecificRule {
  /** Selection of operator of PCR being used for the PCF calculation. If operator is not available in the given list, or if you have followed a sector specific guidance, please select "Other" and include details under "otherOperatorName". */
  operator: ProductOrSectorSpecificRuleOperator;
  /** Names of the product or sector specific rules being used for the PCF calculation. */
  ruleNames: string[];
  /** If operator is Other, then this attribute must be populated with the name of the operator. */
  otherOperatorName?: string;
}

/** References emission factor databases, see [=PACT Methodology=] Section 4.1.3.2. ```json { "name": "ecoinvent", "version": "3.9.1" } ``` */
export interface EmissionFactorDatabases {
  /** Name of the secondary emission factor databases */
  name: string;
  /** Version of the secondary emission factor databases */
  version: string;
}

/** Data type DataQualityIndicators contains the quantitative data quality indicators in conformance with PACT Methodology Section 4.2.3 and Appendix B. Each property is optional until the reference period includes the beginning of calendar year 2025, or later, when all properties MUST be defined. */
export interface DataQualityIndicators {
  /** Percentage of PCF included in the data quality assessment based on the `>5%` emissions threshold. Advisement: [=Decimal=] in 3.0, was Number in 2.x */
  coveragePercent: number;
  /** Quantitative data quality rating (DQR) based on the data quality matrix (See [=PACT Methodology=] Table 9), scoring the technological representativeness of the sources used for PCF calculation based on weighted average of all inputs representing >5% of PCF emissions. The value MUST be a [=decimal=] between `1` and `3` including. Advisement: [=Decimal=] in 3.0, was Number in 2.x */
  technologicalDQR: FloatBetween1And3;
  /** Quantitative data quality rating (DQR) based on the data quality matrix (Table 9), scoring the temporal representativeness of the sources used for PCF calculation based on weighted average of all inputs representing >5% of PCF emissions. The value MUST be between `1` and `3` inclusive. Advisement: [=Decimal=] in 3.0, was Number in 2.x */
  temporalDQR: FloatBetween1And3;
  /** Quantitative data quality rating (DQR) based on the data quality matrix (Table 9), scoring the geographical representativeness of the sources used for PCF calculation based on weighted average of all inputs representing >5% of PCF emissions. The value MUST be between `1` and `3` inclusive. Advisement: [=Decimal=] in 3.0, was Number in 2.x */
  geographicalDQR: FloatBetween1And3;
  /** Quantitative data quality rating (DQR) based on the data quality matrix (Table 9), scoring the completeness of the data collected for PCF calculation based on weighted average of all inputs representing >5% of PCF emissions. The value MUST be between `1` and `3` inclusive. Advisement: [=Decimal=] in 3.0, was Number in 2.x */
  completenessDQR: FloatBetween1And3;
  /** Quantitative data quality rating (DQR) based on the data quality matrix (Table 9), scoring the reliability of the data collected for PCF calculation based on weighted average of all inputs representing >5% of PCF emissions. The value MUST be between `1` and `3` inclusive. Advisement: [=Decimal=] in 3.0, was Number in 2.x */
  reliabilityDQR: FloatBetween1And3;
}

/** Data type `Assurance` contains the assurance in conformance with [=PACT Methodology=] chapter 5 and appendix B. Advisement: the boolean property `assurance` has been REMOVED in version 3.0. The presence of the <{Assurance}> element indicates whether or not the <{CarbonFootprint}> has been assured in line with [=PACT Methodology=] requirements (section 5). */
export interface Assurance {
  /** True or False to indicate whether the PCF has been assured in line with the PACT Methodology. */
  assurance: boolean;
  /** Level of granularity of the emissions data assured, with value equal to - `corporate level` for corporate level - `product line` for product line - `PCF system` for PCF System - `product level` for product level This property MAY be undefined only if the kind of assurance was not performed. */
  coverage?: AssuranceCoverage;
  /** Level of assurance applicable to the PCF, with value equal to - `limited` for limited assurance - `reasonable` for reasonable assurance This property MAY be undefined only if the kind of assurance was not performed. */
  level?: AssuranceLevel;
  /** Boundary of the assurance, with value equal to - `Gate-to-Gate` for Gate-to-Gate - `Cradle-to-Gate` for Cradle-to-Gate. This property MAY be undefined only if the kind of assurance was not performed. */
  boundary?: AssuranceBoundary;
  /** The non-empty name of the independent third party engaged to undertake the assurance. Advisement: OPTIONAL in version 3.0. */
  providerName: string;
  /** The date at which the assurance was completed */
  completedAt?: string;
  /** Name of the standard against which the PCF was assured */
  standardName?: string;
  /** Any additional comments that will clarify the interpretation of the assurance. */
  comments?: string;
}

/** Base class for all events, it follows the CloudEvents specification. */
export interface BaseEvent {
  /** CloudEvents version. */
  specversion: string;
  /** Event identifier. Must be able to uniquely identify the event by source and id. */
  id: string;
  /** The domain and endpoint of the application from which the event originates. */
  source: string;
  /** The time the event occurred. */
  time: string;
}

/** Notification that a ProductFootprint has been published (either new or updated). */
export interface PublishedEvent {
  /** Event type identifier. */
  type: "org.wbcsd.pathfinder.ProductFootprint.Published.v1";
  /** CloudEvents version. */
  specversion: string;
  /** Event identifier. Must be able to uniquely identify the event by source and id. */
  id: string;
  /** The domain and endpoint of the application from which the event originates. */
  source: string;
  /** The time the event occurred. */
  time: string;
  /** data object */
  data: Record<string, unknown>;
}

/** A data recipient request the data owner a ProductFootprint. */
export interface RequestCreatedEvent {
  /** Event type identifier. */
  type: "org.wbcsd.pathfinder.ProductFootprintRequest.Created.v1";
  /** CloudEvents version. */
  specversion: string;
  /** Event identifier. Must be able to uniquely identify the event by source and id. */
  id: string;
  /** The domain and endpoint of the application from which the event originates. */
  source: string;
  /** The time the event occurred. */
  time: string;
  /** data object */
  data: Record<string, unknown>;
}

/** Notification that a ProductFootprint request has been fulfilled. */
export interface RequestFulfilledEvent {
  /** Event type identifier. */
  type?: "org.wbcsd.pathfinder.ProductFootprintRequest.Fulfilled.v1";
  /** CloudEvents version. */
  specversion?: string;
  /** Event identifier. Must be able to uniquely identify the event by source and id. */
  id?: string;
  /** The domain and endpoint of the application from which the event originates. */
  source?: string;
  /** The time the event occurred. */
  time?: string;
  /** data object */
  data?: Record<string, unknown>;
}

/** Notification that a request for a ProductFootprint can not be fulfilled. */
export interface RequestRejectedEvent {
  /** Event type identifier. */
  type?: "org.wbcsd.pathfinder.ProductFootprintRequest.Rejected.v1";
  /** CloudEvents version. */
  specversion?: string;
  /** Event identifier. Must be able to uniquely identify the event by source and id. */
  id?: string;
  /** The domain and endpoint of the application from which the event originates. */
  source?: string;
  /** The time the event occurred. */
  time?: string;
  /** data object */
  data?: Record<string, unknown>;
}

/** Object with error code and descripton. See Chapter "Error Codes" of the Tech Specs for more details. */
export interface Error {
  /** Error code identifier. */
  code: ErrorCode;
  /** Human readable error message. */
  message: string;
}
