version: "3.8"

services:
  pact-directory-local-db:
    image: postgres:15.2-alpine
    # volumes:
    #   - pact-directory-local-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGPASSWORD=postgres
      - POSTGRES_DB=pact_directory_local
    ports:
      - 5432:5432
    networks:
      - pact-network
    restart: unless-stopped
    healthcheck:
      test: pg_isready -U postgres
      interval: 10s
      timeout: 5s
      retries: 5
# volumes:
#   pact-directory-local-db:
#     driver: local
networks:
  pact-network:
